### ISSUE TITLE
Upgrade to latest  kernel version

### ISSUE THREAD

**Issue by santoshmahto7** [iocost-benchmark/linux#7]
At this point of time where resctl-demo system is stable enough, it's better to upgrade our kernel version.
@tejun mentioned there was no breakage of resctl-demo on latest kernel.

**Comment by obbardc** [comment]
Let's see if 6.6 becomes an LTS kernel first

**Comment by obbardc** [comment]
We should prioritise https://github.com/iocost-benchmark/resctl-demo-image-recipe/issues/48

**Comment by obbardc** [comment]
no longer relevant as we don't use a fork anymore :-)
